### ISSUE TITLE
hooks with multiple results stop execution after first result

### ISSUE THREAD

**Issue by dubravcik** [dbt-msft/dbt-sqlserver#80] opened 2021-01-10 20:07 UTC
Hi, I noticed that if a hook contains multiple commands which are returning results, dbt stops execution once it gets the first result. It sometimes happens also when SQL returns some intermediate messages (like rowcount).

To reproduce it I created a useless script just to show that the execution stops right after EXEC sp_who2 and the following steps are not executed. It stops few milliseconds after first EXEC, that's why I added the WAITFOR DELAY.
```sql
{{
  config(   
    pre_hook = " 
       EXEC('DROP VIEW IF EXISTS test_bug_view')    
        
       EXEC sp_who2 -- this returns a result and execution of the hook stops

       WAITFOR DELAY '00:00:04';
       EXEC('CREATE VIEW test_bug_view AS SELECT 1 as col')
       "
  )
}}
SELECT * FROM test_bug_view --this fails, because it wasn't created in the pre-hook
```

As a workaround, now I make sure that there are no intermediate results and it works. For example in EXEC using NO_OUTPUT 

I'd be grateful if somebody can fix it :)

**Comment by mikaelene** [comment] 2021-01-11 06:27
If you executes multiple statements, can you use multiple hooks? One for each statement.

**Comment by swanderz** [comment] 2021-01-11 06:50
to @mikaelene 's point, `pre_hook` let's you pass a list of SQL statements. when I tried this, it works without issue!

```python
{{
  config(   
    pre_hook = [
        "EXEC('DROP VIEW IF EXISTS test_bug_view')",
        "EXEC sp_who2 -- this returns a result and execution of the hook stops",
        "WAITFOR DELAY '00:00:04';",
        "EXEC('CREATE VIEW test_bug_view AS SELECT 1 as col')"
       ]
  )
}}
SELECT * FROM test_bug_view --this fails, because it wasn't created in the pre-hook
```

**Comment by mikaelene** [comment] 2021-01-11 07:24
I think this is the intended behaviour. @dubravcik are you satisfied with this? Can I close this?

**Comment by dubravcik** [comment] 2021-01-11 09:04
Yes I will use the list of SQL statements. Thanks @swanderz  @mikaelene !

I must say that it is unexpected behavior that it silently stops for somebody who doesn't know that it is intended. But it is like that in core dbt right?

**Closed** 2021-01-11 09:08 UTC

**Comment by mikaelene** [comment] 2021-01-11 09:35
> Yes I will use the list of SQL statements. Thanks @swanderz @mikaelene !
> 
> I must say that it is unexpected behavior that it silently stops for somebody who doesn't know that it is intended. But it is like that in core dbt right?

I don't know actually. I meant that if you want to use multiple statements you define them as multiple hooks. Intended usage  is maybe what I meant. The hooks is sent to the database with pyodbc. There is not much we can do about how it is executed. I guess that when dbt gets a result back it sees that statement as complete. dbt only sees that the sql is executed without error. If an error occur, it reports back.
